spring:
  application:
    name: leo-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8012
#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8011/eureka/
#路由
zuul:
  ignored-services: '**'
  routes:
#    soraka-weixin: 'mp/**'
    leo-admin: 'admin/**'
    leo-auth: 'auth/**'
  sensitiveHeaders: Cookie,Set-Cookie
#负载均衡
ribbon:
  ReadTimeout: 10000
#熔断
feign:
  hystrix:
      enabled: true
#认证服务器地址
security:
  auth:
    server: http://localhost:8014
  oauth2:
    client:
      client-id: leo
      client-secret: soraka
    resource:
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址
#日志
logging:
  level:
    com.soraka.auth: DEBUG
    org.springframework.security: DEBUG
